-- 1. Create the table with the exact structure provided
CREATE TABLE latest_scorecards (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, -- Internal unique ID
    event_id TEXT,                                          -- GDACS unique identifier
    country TEXT,
    iso3 TEXT,
    disaster_type TEXT,
    alert_level TEXT,
    severity NUMERIC,
    population NUMERIC,
    vulnerability_index NUMERIC,
    estimated_impact_level TEXT,
    response_recommendation TEXT,
    start_date TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    magnitude NUMERIC,
    mag_unit TEXT,
    aid_dependency_percent_gni NUMERIC,
    historical_risk_score NUMERIC,
    real_time_severity_score NUMERIC,
    financial_dependency_score NUMERIC,
    estimated_required_aid_usd NUMERIC,
    aid_received_usd NUMERIC,
    historical_disaster_count NUMERIC,
    average_deaths NUMERIC,
    average_affected_population NUMERIC,
    estimated_affected_population NUMERIC,
    estimated_deaths NUMERIC,
    risk_category TEXT,
    critical_resource_gap TEXT,
    end_date TIMESTAMPTZ,
    glide_no TEXT,
    magnitude_unit TEXT,
    electricity_access_pct NUMERIC,
    funding_gap_usd NUMERIC,
    triage_score NUMERIC,
    urgency_level TEXT,
    impact_score NUMERIC,
    year INTEGER,
    latitude NUMERIC,
    longitude NUMERIC,
    location_match_status TEXT,
    processed_at TEXT                                       -- Pipeline runtime timestamp
);

-- 2. Disable Row Level Security (RLS)
-- This allows your Python ETL script to INSERT and DELETE records 
-- without needing to set up complex user policies.
ALTER TABLE latest_scorecards DISABLE ROW LEVEL SECURITY;


-- 1. Create the table for historical back-testing and MAE analysis
CREATE TABLE historical_validation (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, -- Internal unique ID
    country TEXT,
    total_deaths NUMERIC,                     -- Actual deaths from EM-DAT history
    estimated_deaths NUMERIC,                 -- What our model predicted
    aid_received_usd NUMERIC,                 -- Historical ODA funds received
    historical_disaster_count NUMERIC,        -- Cumulative burden on the country
    mae_deaths NUMERIC,                       -- Error score (Absolute distance)
    iso3 TEXT,                                -- 3-letter Country Code
    year INTEGER,
    validation_key TEXT,                      -- Format: ISO3_Year_Count (used for de-duplication)
    processed_at TEXT                         -- Pipeline runtime timestamp
);

-- 2. Disable Row Level Security (RLS)
-- This ensures the 'historical' task in main.py can upload 
-- validation data to Supabase freely.
ALTER TABLE historical_validation DISABLE ROW LEVEL SECURITY;